spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: SYSTEM
    password: peng414607
    driver-class-name: oracle.jdbc.OracleDriver
    dbtype: oracle
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
mybatis:
  mapper-locations: classpath:mapper/*.xml

